### ISSUE TITLE
Support parsing Enterprise Architect extended data

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-xmi#3]
![image_2021_03_23T11_17_23_724Z](https://user-images.githubusercontent.com/11865/112142385-7c240480-8c11-11eb-9875-30a59e12cab5.png)

Enterprise Architect's XMI 2.4.2 export function provides two elements:
* `<uml:Model>` which provides UML model information in normal XMI
* `<xmi:Extension>` which provides additional annotation information as entered by the user on top of the underlying UML model

In order to obtain notes and textual description from models we need to obtain from the `<xmi:Extended>` element. 

EXAMPLE:

In `<uml:Model>`, the Duration class (`uml:Class`) has the ID of `EAID_348A493E_C6C6_4f16_B185_F322F9FCC43E`.

The annotations of this class can be found under `<xmi:Extension>` with the `xmi:refid` attribute using the same ID:

```xml
<element xmi:idref="EAID_348A493E_C6C6_4f16_B185_F322F9FCC43E" xmi:type="uml:Class" name="Duration" scope="public">
  <model package="EAPK_A6E46DCC_4D34_4dc0_AD3E_D006699DC90B" tpos="4" ea_localid="187" ea_eleType="element"/>
  <properties documentation="&lt;b&gt;Duration &lt;/b&gt;implements &lt;b&gt;Length&lt;/b&gt; on a &lt;b&gt;Temporal Coordinate System.&lt;/b&gt;"
    isSpecification="false" sType="Class" nType="0" scope="public" stereotype="Union"
    isRoot="false" isLeaf="false" isAbstract="true" isActive="false"/>
```

We need to access this information for model-based documentation.

**Comment by w00lf** [comment]
Implemented in https://github.com/lutaml/lutaml-xmi/pull/5

**Comment by w00lf** [comment]
@ronaldtse can we close this one?

**Comment by ronaldtse** [comment]
Certainly. Thanks @w00lf (next time can you just close after it's implemented?)
