### ISSUE TITLE
Nokogiri should be runtime_dependency

### ISSUE THREAD

**Issue by CAMOBAP** [lutaml/lutaml-xmi#6]
https://github.com/metanorma/metanorma-model-standoc/runs/2485074580?check_suite_focus=true

**Comment by CAMOBAP** [comment]
cc @w00lf

**Comment by w00lf** [comment]
@CAMOBAP is it ok now? I see that build is passing now.

**Comment by CAMOBAP** [comment]
@w00lf thanks, everything is working, closing this one
